version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: lab4
    container_name: lab4-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - lab4
  db:
    image: mysql
    container_name: lab4-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - lab4
  nginx:
    image: nginx
    container_name: lab4-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - lab4
networks:
  lab4:
    driver: bridge